trigger:
  branches:
    include:
      - main

pool:
  name: "Default"

variables:
  azureSubscription: "haipv25-svc"
  webAppName: "haipv25-webapp"
  resourceGroup: "rg_fsa_f1_csm_ec_huutn"

stages:
  # --- Build stage ---
  - stage: Build
    jobs:
      - job: MavenBuild
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: "pom.xml"
              goals: "clean install -DskipTests"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "src/webapp/target/*.jar"
              ArtifactName: "drop"

  # --- Deploy stage ---
  - stage: Deploy
    jobs:
      - deployment: BlueGreen
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    package: "$(Pipeline.Workspace)/drop/*.jar"
